AllCops:
  DisplayCopNames: true
  NewCops: disable
  TargetRubyVersion: 3.3.6

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 150

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 12

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 160

Metrics/PerceivedComplexity:
  Max: 10
